export const TYPES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_USERS: "GET_USERS",
  GET_PRODUCTS_BY_NAME: "GET_PRODUCTS_BY_NAME",
  PRODUCT_DITAILS: "PRODUCT_DITAILS",
  GET_CATEGORIES: "GET_CATEGORIES",
  EDIT_CATEGORIES: "EDIT_CATEGORIES",
  DELETE_CATEGORIES: "DELETE_CATEGORIES",
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
  BY_CATEGORY: "BY_CATEGORY",
  GET_PRODUCTS_ADM: "GET_PRODUCTS_ADM",
  ORDER_ADMIN: "ORDER_ADMIN",
};
